#production
deployment:
  user: myuser
  from: ./
  to: /path/to/deployment
  excludes:
    - app/cache/*
    - app/config/parameters.yml
    - web/bundles/*
    - web/uploads
releases:
  enabled: true
  max: 10
  symlink: current
  directory: releases
hosts:
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - sharedFolderTask: {sharedFiles: 'app/config/parameters.yml,web/uploads'}
