#production
deployment:
  user: root
  from: ./
  to: /var/www
  excludes:
    - app/cache/*
    - app/config/parameters.yml
    - web/bundles/*
    - web/uploads
  strategy: rsync
releases:
  enabled: true
  max: 3
  symlink: current
  directory: releases
hosts:
  - 151.236.62.144
tasks:
  on-deploy:
    - symfony2/assetic-dump: {env: prod}
    - symfony2/assets-install: {env: prod}
    - symfony2/cache-clear: {env: prod}
    - symfony2/cache-warmup: {env: prod}



