imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        mail:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            action_level: critical
            # to also log 400 level errors (but not 404's):
            # action_level: error
            # excluded_404s:
            #     - ^/
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: velaforfun@velaforfun.com
            to_email:   christian1488@hotmail.it
            # or list of recipients
            # to_email:   [dev1@example.com, dev2@example.com, ...]
            subject:    Errore velaforfun
            level:      debug

swiftmailer:
    transport: smtp
    username:  velaforfun
    password:  velaforfun01
    host:  smtp.sendgrid.com
    port:  587