imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
           enum: string
           set: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: AppBundle\Entity\User
        entity_managers:
            default:
                result_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211
                    class: Doctrine\Common\Cache\MemcachedCache
                    instance_class: Memcached
                query_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211
                    class: Doctrine\Common\Cache\MemcachedCache
                    instance_class: Memcached
                query_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211
                    class: Doctrine\Common\Cache\MemcachedCache
                    instance_class: Memcached
                mappings:
                    AppBundle: ~
                    BlogBundle: ~
                    FOSUserBundle: ~
                    CCDNForumForumBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  "Resources/config/doctrine"
                        alias:                ~
                        prefix:               CCDNForum\ForumBundle\Entity
                        is_bundle:            true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secure_area
    user_class:  AppBundle\Entity\User
    registration:
        confirmation:
            enabled:    false # change to true for required email confirmation
        form:
            type: app_user_registration

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: secure_area
    connect:
        confirmation: true
        #account_connector: hwi_oauth.user.provider.fosub_bridge
        #registration_form_handler: hwi_oauth.registration.form.handler.fosub_bridge
        #registration_form: fos_user.registration.form

    resource_owners:
        facebook:
            type:                facebook
            client_id:           575810985813680
            client_secret:       05917e0ff22500a2670f8a1629d8cec3
            options:
                display: popup #dialog is optimized for popup window
    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30

        # mapping between resource owners (see below) and properties
        properties:
            facebook: facebookID

stof_doctrine_extensions:
    default_locale: it_IT
    orm:
        default:
            timestampable: true

eko_feed:
    feeds:
        article:
            title:       'My articles/posts'
            description: 'Latests articles'
            link:        'http://vincent.composieux.fr'
            encoding:    'utf-8'
            author:      'Vincent Composieux' # Only required for Atom feeds

stfalcon_tinymce:
      include_jquery: true
      tinymce_jquery: true

ccdn_forum_forum:
    gateway:
        forum:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\ForumGateway
        category:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\CategoryGateway
        board:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\BoardGateway
        topic:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\TopicGateway
        post:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\PostGateway
        subscription:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\SubscriptionGateway
        registry:
            class:                CCDNForum\ForumBundle\Model\Component\Gateway\RegistryGateway
    repository:
        forum:
            class:                CCDNForum\ForumBundle\Model\Component\Repository\ForumRepository
        category:
            class:                CCDNForum\ForumBundle\Model\Component\Repository\CategoryRepository
        board:
            class:                CCDNForum\ForumBundle\Model\Component\Repository\BoardRepository
        topic:
            class:                CCDNForum\ForumBundle\Model\Component\Repository\TopicRepository
        post:
            class:                CCDNForum\ForumBundle\Model\Component\Repository\PostRepository
        subscription:
            class:                CCDNForum\ForumBundle\Model\Component\Repository\SubscriptionRepository
        registry:
            class:                CCDNForum\ForumBundle\Model\Component\Repository\RegistryRepository
    manager:
        forum:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\ForumManager
        category:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\CategoryManager
        board:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\BoardManager
        topic:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\TopicManager
        post:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\PostManager
        subscription:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\SubscriptionManager
        registry:
            class:                CCDNForum\ForumBundle\Model\Component\Manager\RegistryManager
    model:
        forum:
            class:                CCDNForum\ForumBundle\Model\FrontModel\ForumModel
        category:
            class:                CCDNForum\ForumBundle\Model\FrontModel\CategoryModel
        board:
            class:                CCDNForum\ForumBundle\Model\FrontModel\BoardModel
        topic:
            class:                CCDNForum\ForumBundle\Model\FrontModel\TopicModel
        post:
            class:                CCDNForum\ForumBundle\Model\FrontModel\PostModel
        subscription:
            class:                CCDNForum\ForumBundle\Model\FrontModel\SubscriptionModel
        registry:
            class:                CCDNForum\ForumBundle\Model\FrontModel\RegistryModel
    form:
        handler:
            forum_create:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Forum\ForumCreateFormHandler
            forum_update:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Forum\ForumUpdateFormHandler
            forum_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Forum\ForumDeleteFormHandler
            category_create:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Category\CategoryCreateFormHandler
            category_update:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Category\CategoryUpdateFormHandler
            category_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Category\CategoryDeleteFormHandler
            board_create:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Board\BoardCreateFormHandler
            board_update:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Board\BoardUpdateFormHandler
            board_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Admin\Board\BoardDeleteFormHandler
            topic_create:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Topic\TopicCreateFormHandler
            topic_update:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Topic\TopicUpdateFormHandler
            topic_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\Moderator\Topic\TopicDeleteFormHandler
            change_topics_board:
                class:                CCDNForum\ForumBundle\Form\Handler\Moderator\Topic\TopicChangeBoardFormHandler
            post_create:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Post\PostCreateFormHandler
            post_update:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Post\PostUpdateFormHandler
            post_delete:
                class:                CCDNForum\ForumBundle\Form\Handler\User\Post\PostDeleteFormHandler
            post_unlock:
                class:                CCDNForum\ForumBundle\Form\Handler\Moderator\Post\PostUnlockFormHandler
        type:
            forum_create:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Forum\ForumCreateFormType
            forum_update:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Forum\ForumUpdateFormType
            forum_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Forum\ForumDeleteFormType
            category_create:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Category\CategoryCreateFormType
            category_update:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Category\CategoryUpdateFormType
            category_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Category\CategoryDeleteFormType
            board_create:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Board\BoardCreateFormType
            board_update:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Board\BoardUpdateFormType
            board_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Admin\Board\BoardDeleteFormType
            topic_create:
                class:                CCDNForum\ForumBundle\Form\Type\User\Topic\TopicCreateFormType
            topic_update:
                class:                CCDNForum\ForumBundle\Form\Type\User\Topic\TopicUpdateFormType
            topic_delete:
                class:                CCDNForum\ForumBundle\Form\Type\Moderator\Topic\TopicDeleteFormType
            change_topics_board:
                class:                CCDNForum\ForumBundle\Form\Type\Moderator\Topic\TopicChangeBoardFormType
            post_create:
                class:                AppBundle\Form\Type\PostCreateFormType
            post_update:
                class:                CCDNForum\ForumBundle\Form\Type\User\Post\PostUpdateFormType
            post_delete:
                class:                CCDNForum\ForumBundle\Form\Type\User\Post\PostDeleteFormType
            post_unlock:
                class:                CCDNForum\ForumBundle\Form\Type\Moderator\Post\PostUnlockFormType
