
ibrows_newsletter:
  mandants:
    # generate a secure token for each mandant!
    default:    ThisTokenIsNotSoSecretChangeItdefault
  classes:
    # needed entities - see next step for creating them
    model:
      # most likely fos user
      user:         AppBundle\Entity\User
      # depends on the namespace you set at
      mandant:      AppBundle\Entity\Newsletter\Mandant
      newsletter:   AppBundle\Entity\Newsletter\Newsletter
      subscriber:   AppBundle\Entity\Newsletter\Subscriber
      design:       AppBundle\Entity\Newsletter\Design
      block:        AppBundle\Entity\Newsletter\Block
      group:        AppBundle\Entity\Newsletter\Group
      readlog:      AppBundle\Entity\Newsletter\Log\ReadLog
      sendlog:      AppBundle\Entity\Newsletter\Log\SendLog
      sendsettings: AppBundle\Entity\Newsletter\SendSettings
      mailjob:      AppBundle\Entity\Newsletter\MailJob
      unsubscribelog: AppBundle\Entity\Newsletter\Log\UnsubscribeLog
  filesystem:
      block:
        # where to store uploaded files (e.g. image uploads)
        directory:  %kernel.root_dir%/../web/uploads/block
        # absolute path to the uploaded files
        public:     /uploads/block