imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/logs/(environment).log
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            # log *all* messages (debug is lowest level)
            level: debug

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error


swiftmailer:
     disable_delivery:  true

assetic:
    use_controller: true


 #wall_poster:
  #   facebook:
  #       access_token: ''
  #       app_id: 934348009960166
  #       app_secret: 84c4e12ab4042dd303245a991bf2fb20
   #      page: 508027799222045
   # twitter:
    #    api_key: TWITTER_APP_KEY
   #     api_secret: TWITTER_APP_SECRET
   #     access_token: TWITTER_ACCESS_TOKEN
   #     access_secret:  TWITTER_ACCESS_TOKEN_SECRET