


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_registration_register:
    defaults: { _controller: AppBundle:Registration:register }
    pattern:   /register

fos_user_registration_check_email:
    defaults: { _controller: AppBundle:Registration:checkEmail }
    pattern:   /register/check-email

fos_user_registration_confirm:
    defaults: { _controller: AppBundle:Registration:checkEmail }
    pattern:   /register/confirm/{token}

fos_user_registration_confirmed:
    defaults: { _controller: AppBundle:Registration:confirmed }
    pattern:   /register/confirmed

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


app:
    resource: "@AppBundle/Resources/config/routing.yml"

archivio:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /archivio


hwi_oauth_service_redirect:
    defaults: { _controller: AppBundle:Secured:redirectToService }
    pattern:   /secure_area/connect/{service}

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /secure_area/connect

hwi_oauth_connect_service:
    defaults: { _controller: AppBundle:Secured:connectService }
    pattern:   /secure_area/connect/service/{service}

hwi_oauth_connect_registration:
    defaults: { _controller: AppBundle:Secured:registration }
    pattern:   /secure_area/connect/registration/{key}

facebook_login:
    pattern: /secure_area/login/check-facebook

ccdn_homepage:
    pattern: /forum
    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: it, forumName: VelaForFun }

CCDNForumForumBundle-Admin:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin.yml"
    prefix: /forum/admin
    defaults: { _locale: it }


CCDNForumForumBundle-Admin-Forum:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-forum.yml"
    prefix: /forum/admin/manage-forums
    defaults: { _locale: it }

CCDNForumForumBundle-Admin-Category:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-category.yml"
    prefix: /forum/admin/manage-categories
    defaults: { _locale: it }
CCDNForumForumBundle-Admin-Board:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-board.yml"
    prefix: /forum/admin/manage-boards
    defaults: { _locale: it }
CCDNForumForumBundle-Admin-Topic:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-topic.yml"
    prefix: /forum/admin/manage-topics
    defaults: { _locale: it }
CCDNForumForumBundle-Admin-Post:
    resource: "@CCDNForumForumBundle/Resources/config/routing/admin-post.yml"
    prefix: /forum/admin/manage-posts
    defaults: { _locale: it }


CCDNForumForumBundle-Moderator-Topic:
    resource: "@CCDNForumForumBundle/Resources/config/routing/moderator-topic.yml"
    prefix: /forum/{forumName}/moderator/manage-topics

CCDNForumForumBundle-Moderator-Post:
    resource: "@CCDNForumForumBundle/Resources/config/routing/moderator-post.yml"
    prefix: /forum/{forumName}/moderator/manage-posts



CCDNForumForumBundle-User-Category:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-category.yml"
    prefix: /forum
    defaults: { _locale: it }

CCDNForumForumBundle-User-Board:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-board.yml"
    prefix: /forum/{forumName}/board
    defaults: { _locale: it }
CCDNForumForumBundle-User-Topic:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-topic.yml"
    prefix: /forum/{forumName}/topic
    defaults: { _locale: it }

CCDNForumForumBundle-User-Post:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-post.yml"
    prefix: /forum/{forumName}/post
    defaults: { _locale: it }

CCDNForumForumBundle-User-Subscription:
    resource: "@CCDNForumForumBundle/Resources/config/routing/user-subscription.yml"
    prefix: /forum/{forumName}/subscription
    defaults: { _locale: it }

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# IbrowsNewsletter
ibrows_newsletter:
    resource: "@IbrowsNewsletterBundle/Controller/"
    type:     annotation
    prefix:   /newsletter