security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        secure_area:
            form_login:
                provider:               fos_userbundle
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
              #  csrf_provider:          form.csrf_provider
                success_handler: app.handler.login_success_handler
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 giorni in secondi
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            pattern: ^/

            oauth:
                failure_path: /secure_area/connect
                login_path: /login
                check_path: /secure_area/connect
                provider: fos_userbundle
                resource_owners:
                    facebook:           "/secure_area/login/check-facebook"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            anonymous:    true
            logout:
                path:           /logout
                success_handler: app.handler.logout_success_handler

    access_control:
     - { path: ^/secure_area/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: /annuncio-imbarco/cerca-annuncio, roles: ROLE_USER }
     - { path: /annuncio-scambio-posto/cerca-annuncio, roles: ROLE_USER }

    # - { path: /modifica/, roles: ROLE_ADMIN }
    # - { path: /elimina/, roles: ROLE_ADMIN }
    # - { path: /list, roles: ROLE_ADMIN }
    role_hierarchy:
           ROLE_ADMIN:       ROLE_USER
           ROLE_SUPER_ADMIN: ROLE_ADMIN

