# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app_user.registration.form.type:
          class: AppBundle\Form\Type\RegistrationFormType
          tags:
              - { name: form.type, alias: app_user_registration }

  weather.client:
      class: "%guzzle.client.class%"
      tags:
        - { name: guzzle.client }
      arguments:
        - "%webservice_weather_url%"

  app.twig.menu_extension:
      class: AppBundle\Twig\Extension\MenuVelaExtension
      tags:
        - { name: twig.extension }
      calls:
        - [ setContainer,[ @service_container ] ]

  app.calendar_listener:
      class: AppBundle\EventListener\CalendarEventListener
      tags:
        - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
      arguments:
        - "@doctrine.orm.entity_manager"

  old_routing.kernel.request.router_listener:
          class: AppBundle\EventListener\OldRoutingRedirectListener
          arguments:
              - "@logger"
          tags:
              - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 32 }
              - { name: monolog.logger, channel: request }
          calls:
              - [ setContainer,[ @service_container ] ]

  forum.listener:
          class: AppBundle\EventListener\VelaForumListener
          tags:
              - { name: kernel.event_subscriber }

  app.handler.logout_success_handler:
          class:  AppBundle\Services\LogoutSuccessHandlerService
          arguments:  [@router]
          tags:
              - { name: 'monolog.logger', channel: 'security' }

  app.handler.login_success_handler:
            class:  AppBundle\Services\LoginSuccessHandlerService
            arguments:  [@router, @security.context]
            tags:
                - { name: 'monolog.logger', channel: 'security' }