
default:
    resource: "@BlogBundle/Controller/DefaultController.php"
    type:     annotation

categoria:
    resource: "@BlogBundle/Controller/CategoriaController.php"
    type:     annotation

articolo:
    resource: "@BlogBundle/Controller/ArticoloController.php"
    type:     annotation