app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

video:
    resource: "@AppBundle/Controller/VideoController.php"
    type:     annotation
    prefix:   /video

porti:
    resource: "@AppBundle/Controller/PortoController.php"
    type:     annotation
    prefix:   /porti

nodi:
    resource: "@AppBundle/Controller/NodoController.php"
    type:     annotation
    prefix:   /nodi

barche:
    resource: "@AppBundle/Controller/BarcaController.php"
    type:     annotation
    prefix:   /barche


menu:
    resource: "@AppBundle/Controller/MenuController.php"
    type:     annotation
    prefix:   /menu

nodomenu:
    resource: "@AppBundle/Controller/NodoMenuController.php"
    type:     annotation
    prefix:   /nodomenu

partner:
    resource: "@AppBundle/Controller/PartnerController.php"
    type:     annotation
    prefix:   /partner

eventi:
    resource: "@AppBundle/Controller/EventoController.php"
    type:     annotation
    prefix:   /evento

annuncio_imbarco:
    resource: "@AppBundle/Controller/AnnuncioImbarcoController.php"
    type:     annotation
    prefix:   /annuncio-imbarco