video:
    resource: "@AppBundle/Controller/VideoController.php"
    type:     annotation
    prefix:   /video

porti:
    resource: "@AppBundle/Controller/PortoController.php"
    type:     annotation
    prefix:   /porti

nodi:
    resource: "@AppBundle/Controller/NodoController.php"
    type:     annotation
    prefix:   /nodi

images:
    resource: "@AppBundle/Controller/ImageController.php"
    type:     annotation
    prefix:   /images

foto:
    resource: "@AppBundle/Controller/FotoController.php"
    type:     annotation
    prefix:   /foto

pagina_statica:
    resource: "@AppBundle/Controller/PaginaStaticaController.php"
    type:     annotation
    prefix:   /cms

segnali:
    resource: "@AppBundle/Controller/SegnaleController.php"
    type:     annotation
    prefix:   /codice-internazionale


nomi_barca:
    resource: "@AppBundle/Controller/NomeBarcaController.php"
    type:     annotation
    prefix:   /nomi-barca


menu:
    resource: "@AppBundle/Controller/MenuController.php"
    type:     annotation
    prefix:   /menu


galleria_foto:
    resource: "@AppBundle/Controller/GalleriaFotoController.php"
    type:     annotation
    prefix:   /galleria-foto

nodomenu:
    resource: "@AppBundle/Controller/NodoMenuController.php"
    type:     annotation
    prefix:   /nodomenu

partner:
    resource: "@AppBundle/Controller/PartnerController.php"
    type:     annotation
    prefix:   /partner

eventi:
    resource: "@AppBundle/Controller/EventoController.php"
    type:     annotation
    prefix:   /evento

annuncio_imbarco:
    resource: "@AppBundle/Controller/AnnuncioImbarcoController.php"
    type:     annotation
    prefix:   /annuncio-imbarco

annuncio:
    resource: "@AppBundle/Controller/AnnuncioController.php"
    type:     annotation
    prefix:   /annuncio

annuncio_scambio_posto:
    resource: "@AppBundle/Controller/AnnuncioScambioPostoController.php"
    type:     annotation
    prefix:   /annuncio-scambio-posto

segnalazione_portolano:
    resource: "@AppBundle/Controller/SegnalazionePortolanoController.php"
    type:     annotation
    prefix:   /segnalazione-portolano

commenti_porto:
    resource: "@AppBundle/Controller/CommentoPortoController.php"
    type:     annotation
    prefix:   /commento-porto



user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /utenti


app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /